version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oauth2
      MYSQL_USER: alan
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"